In [1]:
import numpy as np
import ptan

There are 3 types of action, we are considering:

Argmax selector: apply argmax in second axis of tensor

In [2]:
q_vals = np.array([[1, 2, 3], [5, 7, 4]])
q_vals

array([[1, 2, 3],
       [5, 7, 4]])

In [3]:
selector = ptan.actions.ArgmaxActionSelector()
selector(q_vals)

array([2, 1], dtype=int64)

When we need a bit more randomness

In [5]:
selector = ptan.actions.EpsilonGreedyActionSelector(epsilon=0.0)
selector(q_vals)

array([2, 1], dtype=int64)

when we want to choose action following a distribution, we normalize input then apply ProbabilityActionSelector()

In [8]:
selector = ptan.actions.ProbabilityActionSelector()

In [9]:
for _ in range(10):
    input = np.array([
        [0.1, 0.8, 0.1], 
        [0.0, 0.0, 1.0],
        [0.5, 0.5, 0.0]
    ])
    acts = selector(input)
    print(acts)

[1 2 1]
[1 2 1]
[1 2 0]
[0 2 1]
[1 2 1]
[1 2 0]
[1 2 0]
[0 2 1]
[1 2 1]
[1 2 1]
